### ISSUE TITLE
Problem importing rstrip

### ISSUE THREAD

**Issue by bolkowitz** [unicornsasfuel/aesbrute#1]
Using Python 3.7.0 on Windows 10, the method rstrip from string cannot be imported. 

> Traceback (most recent call last):
>   File "aes_brute.py", line 9, in <module>
>     from string import rstrip
> ImportError: cannot import name 'rstrip' from 'string'

Lines 38 and 47 in aes_brute.py use rstrip below:

`samples = map(rstrip, sample_fh.readlines())`
`keys = map(rstrip, keys_fh.readlines())`

Please advise, thank you!

**Comment by unicornsasfuel** [comment]
aesbrute expects Python 2.7. I have no plans to migrate this to use Python3, since this tool exists mostly as a proof of concept and will be replaced by a rewrite in a language that can meaningfully parallelize tasks and thereby greatly improve cracking speed.

I'll update the documentation to specify 2.7. Thanks!
